/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'id' : bigint,
  'title' : string,
  'availableCopies' : bigint,
  'isbn' : string,
  'isActive' : boolean,
  'author' : string,
  'totalCopies' : bigint,
  'category' : Category,
  'classification' : Classification,
}
export type Category = { 'law' : null } |
  { 'biology' : null } |
  { 'computerscience' : null } |
  { 'math' : null } |
  { 'nonFiction' : null } |
  { 'economics' : null } |
  { 'chemistry' : null } |
  { 'literature' : null } |
  { 'philosophy' : null } |
  { 'physics' : null } |
  { 'generalKnowledge' : null } |
  { 'psychology' : null } |
  { 'fiction' : null };
export type Classification = { 'col' : null } |
  { 'ddc' : null };
export interface DashboardStats {
  'totalStudents' : bigint,
  'totalBooks' : bigint,
}
export interface GateEntry {
  'id' : bigint,
  'exitTime' : [] | [Time],
  'entryTime' : Time,
  'studentRegisterId' : string,
}
export interface Issue {
  'id' : bigint,
  'issueDate' : Time,
  'bookId' : bigint,
  'isReturned' : boolean,
  'borrower' : Principal,
  'returnDate' : [] | [Time],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBook' : ActorMethod<
    [string, string, string, Classification, Category, bigint],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getBook' : ActorMethod<[bigint], [] | [Book]>,
  'getCallerIssuedBooks' : ActorMethod<[], Array<Issue>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getGateEntriesByStudent' : ActorMethod<[string], Array<GateEntry>>,
  'getGateVisitCount' : ActorMethod<[string], bigint>,
  'getIssuedBooksCount' : ActorMethod<[Principal], bigint>,
  'getTodayGateEntries' : ActorMethod<[], Array<GateEntry>>,
  'getUserIssuedBooks' : ActorMethod<[Principal], Array<Issue>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'issueBook' : ActorMethod<[bigint], [] | [bigint]>,
  'markGateExit' : ActorMethod<[bigint], boolean>,
  'recordGateEntry' : ActorMethod<[string], bigint>,
  'removeBook' : ActorMethod<[bigint], boolean>,
  'returnBook' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchBooksByAuthor' : ActorMethod<[string], Array<Book>>,
  'searchBooksByCategory' : ActorMethod<[Category], Array<Book>>,
  'searchBooksByTitle' : ActorMethod<[string], Array<Book>>,
  'updateBook' : ActorMethod<
    [bigint, string, string, string, Classification, Category, bigint, boolean],
    boolean
  >,
  'updateDashboardStats' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];