/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Classification = IDL.Variant({
  'col' : IDL.Null,
  'ddc' : IDL.Null,
});
export const Category = IDL.Variant({
  'law' : IDL.Null,
  'biology' : IDL.Null,
  'computerscience' : IDL.Null,
  'math' : IDL.Null,
  'nonFiction' : IDL.Null,
  'economics' : IDL.Null,
  'chemistry' : IDL.Null,
  'literature' : IDL.Null,
  'philosophy' : IDL.Null,
  'physics' : IDL.Null,
  'generalKnowledge' : IDL.Null,
  'psychology' : IDL.Null,
  'fiction' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Book = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'availableCopies' : IDL.Nat,
  'isbn' : IDL.Text,
  'isActive' : IDL.Bool,
  'author' : IDL.Text,
  'totalCopies' : IDL.Nat,
  'category' : Category,
  'classification' : Classification,
});
export const Time = IDL.Int;
export const Issue = IDL.Record({
  'id' : IDL.Nat,
  'issueDate' : Time,
  'bookId' : IDL.Nat,
  'isReturned' : IDL.Bool,
  'borrower' : IDL.Principal,
  'returnDate' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalStudents' : IDL.Nat,
  'totalBooks' : IDL.Nat,
});
export const GateEntry = IDL.Record({
  'id' : IDL.Nat,
  'exitTime' : IDL.Opt(Time),
  'entryTime' : Time,
  'studentRegisterId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Classification, Category, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getBook' : IDL.Func([IDL.Nat], [IDL.Opt(Book)], ['query']),
  'getCallerIssuedBooks' : IDL.Func([], [IDL.Vec(Issue)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getGateEntriesByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GateEntry)],
      ['query'],
    ),
  'getGateVisitCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getIssuedBooksCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getTodayGateEntries' : IDL.Func([], [IDL.Vec(GateEntry)], ['query']),
  'getUserIssuedBooks' : IDL.Func([IDL.Principal], [IDL.Vec(Issue)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'issueBook' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
  'markGateExit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'recordGateEntry' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'removeBook' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'returnBook' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchBooksByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'searchBooksByCategory' : IDL.Func([Category], [IDL.Vec(Book)], ['query']),
  'searchBooksByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'updateBook' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Classification,
        Category,
        IDL.Nat,
        IDL.Bool,
      ],
      [IDL.Bool],
      [],
    ),
  'updateDashboardStats' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Classification = IDL.Variant({ 'col' : IDL.Null, 'ddc' : IDL.Null });
  const Category = IDL.Variant({
    'law' : IDL.Null,
    'biology' : IDL.Null,
    'computerscience' : IDL.Null,
    'math' : IDL.Null,
    'nonFiction' : IDL.Null,
    'economics' : IDL.Null,
    'chemistry' : IDL.Null,
    'literature' : IDL.Null,
    'philosophy' : IDL.Null,
    'physics' : IDL.Null,
    'generalKnowledge' : IDL.Null,
    'psychology' : IDL.Null,
    'fiction' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Book = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'availableCopies' : IDL.Nat,
    'isbn' : IDL.Text,
    'isActive' : IDL.Bool,
    'author' : IDL.Text,
    'totalCopies' : IDL.Nat,
    'category' : Category,
    'classification' : Classification,
  });
  const Time = IDL.Int;
  const Issue = IDL.Record({
    'id' : IDL.Nat,
    'issueDate' : Time,
    'bookId' : IDL.Nat,
    'isReturned' : IDL.Bool,
    'borrower' : IDL.Principal,
    'returnDate' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalStudents' : IDL.Nat,
    'totalBooks' : IDL.Nat,
  });
  const GateEntry = IDL.Record({
    'id' : IDL.Nat,
    'exitTime' : IDL.Opt(Time),
    'entryTime' : Time,
    'studentRegisterId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Classification, Category, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getBook' : IDL.Func([IDL.Nat], [IDL.Opt(Book)], ['query']),
    'getCallerIssuedBooks' : IDL.Func([], [IDL.Vec(Issue)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getGateEntriesByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GateEntry)],
        ['query'],
      ),
    'getGateVisitCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getIssuedBooksCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getTodayGateEntries' : IDL.Func([], [IDL.Vec(GateEntry)], ['query']),
    'getUserIssuedBooks' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Issue)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'issueBook' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
    'markGateExit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'recordGateEntry' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'removeBook' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'returnBook' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchBooksByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'searchBooksByCategory' : IDL.Func([Category], [IDL.Vec(Book)], ['query']),
    'searchBooksByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'updateBook' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Classification,
          Category,
          IDL.Nat,
          IDL.Bool,
        ],
        [IDL.Bool],
        [],
      ),
    'updateDashboardStats' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };