/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Issue {
    id: bigint;
    issueDate: Time;
    bookId: bigint;
    isReturned: boolean;
    borrower: Principal;
    returnDate?: Time;
}
export interface GateEntry {
    id: bigint;
    exitTime?: Time;
    entryTime: Time;
    studentRegisterId: string;
}
export interface Book {
    id: bigint;
    title: string;
    availableCopies: bigint;
    isbn: string;
    isActive: boolean;
    author: string;
    totalCopies: bigint;
    category: Category;
    classification: Classification;
}
export interface DashboardStats {
    totalStudents: bigint;
    totalBooks: bigint;
}
export interface UserProfile {
    name: string;
}
export enum Category {
    law = "law",
    biology = "biology",
    computerscience = "computerscience",
    math = "math",
    nonFiction = "nonFiction",
    economics = "economics",
    chemistry = "chemistry",
    literature = "literature",
    philosophy = "philosophy",
    physics = "physics",
    generalKnowledge = "generalKnowledge",
    psychology = "psychology",
    fiction = "fiction"
}
export enum Classification {
    col = "col",
    ddc = "ddc"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBook(title: string, author: string, isbn: string, classification: Classification, category: Category, totalCopies: bigint): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllBooks(): Promise<Array<Book>>;
    getBook(bookId: bigint): Promise<Book | null>;
    getCallerIssuedBooks(): Promise<Array<Issue>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getGateEntriesByStudent(studentRegisterId: string): Promise<Array<GateEntry>>;
    getGateVisitCount(studentRegisterId: string): Promise<bigint>;
    getIssuedBooksCount(user: Principal): Promise<bigint>;
    getTodayGateEntries(): Promise<Array<GateEntry>>;
    getUserIssuedBooks(user: Principal): Promise<Array<Issue>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    issueBook(bookId: bigint): Promise<bigint | null>;
    markGateExit(entryId: bigint): Promise<boolean>;
    recordGateEntry(studentRegisterId: string): Promise<bigint>;
    removeBook(bookId: bigint): Promise<boolean>;
    returnBook(issueId: bigint): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchBooksByAuthor(searchTerm: string): Promise<Array<Book>>;
    searchBooksByCategory(category: Category): Promise<Array<Book>>;
    searchBooksByTitle(searchTerm: string): Promise<Array<Book>>;
    updateBook(bookId: bigint, title: string, author: string, isbn: string, classification: Classification, category: Category, totalCopies: bigint, isActive: boolean): Promise<boolean>;
    updateDashboardStats(totalBooks: bigint, totalStudents: bigint): Promise<void>;
}
import type { Book as _Book, Category as _Category, Classification as _Classification, GateEntry as _GateEntry, Issue as _Issue, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBook(arg0: string, arg1: string, arg2: string, arg3: Classification, arg4: Category, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBook(arg0, arg1, arg2, to_candid_Classification_n1(this._uploadFile, this._downloadFile, arg3), to_candid_Category_n3(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBook(arg0, arg1, arg2, to_candid_Classification_n1(this._uploadFile, this._downloadFile, arg3), to_candid_Category_n3(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllBooks(): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBooks();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBooks();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBook(arg0: bigint): Promise<Book | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBook(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBook(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerIssuedBooks(): Promise<Array<Issue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerIssuedBooks();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerIssuedBooks();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getGateEntriesByStudent(arg0: string): Promise<Array<GateEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGateEntriesByStudent(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGateEntriesByStudent(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGateVisitCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getGateVisitCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGateVisitCount(arg0);
            return result;
        }
    }
    async getIssuedBooksCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getIssuedBooksCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIssuedBooksCount(arg0);
            return result;
        }
    }
    async getTodayGateEntries(): Promise<Array<GateEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayGateEntries();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayGateEntries();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserIssuedBooks(arg0: Principal): Promise<Array<Issue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserIssuedBooks(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserIssuedBooks(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async issueBook(arg0: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.issueBook(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.issueBook(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async markGateExit(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markGateExit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markGateExit(arg0);
            return result;
        }
    }
    async recordGateEntry(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordGateEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordGateEntry(arg0);
            return result;
        }
    }
    async removeBook(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBook(arg0);
            return result;
        }
    }
    async returnBook(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.returnBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.returnBook(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchBooksByAuthor(arg0: string): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchBooksByAuthor(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchBooksByAuthor(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchBooksByCategory(arg0: Category): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchBooksByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchBooksByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchBooksByTitle(arg0: string): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchBooksByTitle(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchBooksByTitle(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBook(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Classification, arg5: Category, arg6: bigint, arg7: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBook(arg0, arg1, arg2, arg3, to_candid_Classification_n1(this._uploadFile, this._downloadFile, arg4), to_candid_Category_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBook(arg0, arg1, arg2, arg3, to_candid_Classification_n1(this._uploadFile, this._downloadFile, arg4), to_candid_Category_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async updateDashboardStats(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDashboardStats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDashboardStats(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Book_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Book): Book {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Classification_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Classification): Classification {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_GateEntry_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GateEntry): GateEntry {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Issue_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Issue): Issue {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Book]): Book | null {
    return value.length === 0 ? null : from_candid_Book_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    issueDate: _Time;
    bookId: bigint;
    isReturned: boolean;
    borrower: Principal;
    returnDate: [] | [_Time];
}): {
    id: bigint;
    issueDate: Time;
    bookId: bigint;
    isReturned: boolean;
    borrower: Principal;
    returnDate?: Time;
} {
    return {
        id: value.id,
        issueDate: value.issueDate,
        bookId: value.bookId,
        isReturned: value.isReturned,
        borrower: value.borrower,
        returnDate: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.returnDate))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    exitTime: [] | [_Time];
    entryTime: _Time;
    studentRegisterId: string;
}): {
    id: bigint;
    exitTime?: Time;
    entryTime: Time;
    studentRegisterId: string;
} {
    return {
        id: value.id,
        exitTime: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.exitTime)),
        entryTime: value.entryTime,
        studentRegisterId: value.studentRegisterId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    availableCopies: bigint;
    isbn: string;
    isActive: boolean;
    author: string;
    totalCopies: bigint;
    category: _Category;
    classification: _Classification;
}): {
    id: bigint;
    title: string;
    availableCopies: bigint;
    isbn: string;
    isActive: boolean;
    author: string;
    totalCopies: bigint;
    category: Category;
    classification: Classification;
} {
    return {
        id: value.id,
        title: value.title,
        availableCopies: value.availableCopies,
        isbn: value.isbn,
        isActive: value.isActive,
        author: value.author,
        totalCopies: value.totalCopies,
        category: from_candid_Category_n10(_uploadFile, _downloadFile, value.category),
        classification: from_candid_Classification_n12(_uploadFile, _downloadFile, value.classification)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    law: null;
} | {
    biology: null;
} | {
    computerscience: null;
} | {
    math: null;
} | {
    nonFiction: null;
} | {
    economics: null;
} | {
    chemistry: null;
} | {
    literature: null;
} | {
    philosophy: null;
} | {
    physics: null;
} | {
    generalKnowledge: null;
} | {
    psychology: null;
} | {
    fiction: null;
}): Category {
    return "law" in value ? Category.law : "biology" in value ? Category.biology : "computerscience" in value ? Category.computerscience : "math" in value ? Category.math : "nonFiction" in value ? Category.nonFiction : "economics" in value ? Category.economics : "chemistry" in value ? Category.chemistry : "literature" in value ? Category.literature : "philosophy" in value ? Category.philosophy : "physics" in value ? Category.physics : "generalKnowledge" in value ? Category.generalKnowledge : "psychology" in value ? Category.psychology : "fiction" in value ? Category.fiction : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    col: null;
} | {
    ddc: null;
}): Classification {
    return "col" in value ? Classification.col : "ddc" in value ? Classification.ddc : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Issue>): Array<Issue> {
    return value.map((x)=>from_candid_Issue_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GateEntry>): Array<GateEntry> {
    return value.map((x)=>from_candid_GateEntry_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Book>): Array<Book> {
    return value.map((x)=>from_candid_Book_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Classification_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Classification): _Classification {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Classification): {
    col: null;
} | {
    ddc: null;
} {
    return value == Classification.col ? {
        col: null
    } : value == Classification.ddc ? {
        ddc: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    law: null;
} | {
    biology: null;
} | {
    computerscience: null;
} | {
    math: null;
} | {
    nonFiction: null;
} | {
    economics: null;
} | {
    chemistry: null;
} | {
    literature: null;
} | {
    philosophy: null;
} | {
    physics: null;
} | {
    generalKnowledge: null;
} | {
    psychology: null;
} | {
    fiction: null;
} {
    return value == Category.law ? {
        law: null
    } : value == Category.biology ? {
        biology: null
    } : value == Category.computerscience ? {
        computerscience: null
    } : value == Category.math ? {
        math: null
    } : value == Category.nonFiction ? {
        nonFiction: null
    } : value == Category.economics ? {
        economics: null
    } : value == Category.chemistry ? {
        chemistry: null
    } : value == Category.literature ? {
        literature: null
    } : value == Category.philosophy ? {
        philosophy: null
    } : value == Category.physics ? {
        physics: null
    } : value == Category.generalKnowledge ? {
        generalKnowledge: null
    } : value == Category.psychology ? {
        psychology: null
    } : value == Category.fiction ? {
        fiction: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
